from pathlib import Path
from typing import Any, Dict, List, Optional, Union


def write_review(
    path: Union[str, Path],
    goal: str,
    selected_dorks: List[str],
    findings: List[Dict[str, Any]],
    metadata: Optional[Dict[str, str]] = None,
    reasoning: Optional[str] = None,
) -> None:
    review_path = Path(path)
    review_path.parent.mkdir(parents=True, exist_ok=True)

    metadata_lines = []
    if metadata:
        metadata_lines = [f"- **{key}**: {value}" for key, value in metadata.items()]

    with review_path.open("w", encoding="utf-8") as handle:
        handle.write("# Google Dork Review\n\n")
        handle.write(f"**Objective:** {goal.strip()}\n\n")
        if metadata_lines:
            handle.write("## Agent Metadata\n\n")
            handle.write("\n".join(metadata_lines))
            handle.write("\n\n")

        handle.write("## Selected Google Dorks\n\n")
        for dork in selected_dorks:
            handle.write(f"- `{dork}`\n")
        handle.write("\n")

        handle.write("## Findings\n\n")
        for item in findings:
            handle.write(f"### Query: `{item['query']}`\n\n")
            urls = item.get("results", [])
            if not urls:
                handle.write("No results were captured for this query.\n\n")
                continue
            for result in urls:
                handle.write(f"- [{result['title']}]({result['url']})\n")
                if result.get("snippet"):
                    handle.write(f"  - {result['snippet']}\n")
            handle.write("\n")

        if reasoning:
            handle.write("## Reasoning\n\n")
            handle.write(reasoning.strip() + "\n\n")

        handle.write("## Notes\n\n")
        handle.write(
            "This report was generated by the dork automation agent. Review the selected dorks, verify that scraped results are relevant, and refine the search goals before any further analysis."
        )
